"""SOP 06 - JSON plan data -> professional markdown test plan.

This is a deterministic renderer. The LLM never touches the template (BR-6).
"""
from datetime import datetime


def render(plan: dict, ticket: dict, model: str = "") -> str:
    """Render the JSON plan data into a formatted markdown test plan.

    Args:
        plan: The JSON plan_data from the LLM (plan_build.py output).
        ticket: The normalized ticket dict.
        model: The LLM model name for attribution.

    Returns:
        Complete markdown test plan string.
    """
    meta = plan.get("plan_meta", {})
    key = ticket["key"]

    lines = []
    lines.append(f"# Test Plan: {ticket['summary']}")
    lines.append("")
    lines.append(f"**Jira Ticket:** [{key}]({ticket['url']})")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}")
    if model:
        lines.append(f"**Generated by:** {model}")
    lines.append(f"**Ticket Status:** {ticket.get('status', 'Unknown')}")
    lines.append(f"**Priority:** {ticket.get('priority', 'Not set')}")
    lines.append("")

    # --- 1. Objective ---
    lines.append("## 1. Objective")
    lines.append("")
    obj = plan.get("objective", {})
    lines.append(obj.get("text",
        "_(Not specified — requires product owner input)_"))
    justified = obj.get("justified_by", [])
    if justified:
        lines.append(f"> Source: {', '.join(justified)}")
    lines.append("")

    # --- 2. Scope ---
    lines.append("## 2. Scope")
    lines.append("")
    scope = plan.get("scope", {})

    lines.append("### In Scope")
    for item in scope.get("in_scope", []):
        src = item.get("justified_by", "No trace")
        lines.append(f"- **{item.get('item', '?')}**  ")
        lines.append(f"  _Justified by: {src}_")
    if not scope.get("in_scope"):
        lines.append("_(No scope items defined — requires product owner input)_")
    lines.append("")

    lines.append("### Out of Scope")
    for item in scope.get("out_of_scope", []):
        src = item.get("justified_by", "No trace")
        lines.append(f"- **{item.get('item', '?')}**")
        lines.append(f"  _Reason: {src}_")
    if not scope.get("out_of_scope"):
        lines.append("_(Nothing explicitly excluded)_")
    lines.append("")

    # --- 3. Test Environment ---
    lines.append("## 3. Test Environment")
    lines.append("")
    lines.append(plan.get("test_environment",
        "_(Not specified in ticket — requires clarification)_"))

    # --- 4. Test Strategy ---
    lines.append("## 4. Test Strategy")
    lines.append("")
    lines.append(plan.get("test_strategy",
        "_(Not specified — requires QA architect input)_"))

    # --- 5. Test Data ---
    lines.append("## 5. Test Data")
    lines.append("")
    lines.append(plan.get("test_data",
        "_(Not specified in ticket — requires clarification)_"))
    lines.append("")

    # ---6. Defect Reporting ---
    lines.append("## 6. Defect Reporting")
    lines.append("")
    lines.append(plan.get("defect_reporting",
        "_(Not specified — use standard Jira bug reporting workflow)_"))
    lines.append("")

    # --- 7. Entry Criteria ---
    lines.append("## 7. Entry Criteria")
    lines.append("")
    lines.append(plan.get("entry_criteria",
        "_(Not specified in ticket — requires product owner input)_"))
    lines.append("")

    # --- 8. Exit Criteria ---
    lines.append("## 8. Exit Criteria")
    lines.append("")
    lines.append(plan.get("exit_criteria",
        "_(Not specified in ticket — requires product owner input)_"))
    lines.append("")

    # --- 9. Test Deliverables ---
    lines.append("## 9. Test Deliverables")
    lines.append("")
    lines.append(plan.get("test_deliverables",
        "_(Not specified — standard test plan and test cases)_"))
    lines.append("")

    # --- 10. Test Schedule ---
    lines.append("## 10. Test Schedule")
    lines.append("")
    lines.append(plan.get("test_schedule",
        "_(Not specified in ticket — requires project manager input)_"))
    lines.append("")

    # --- 11. Risks and Mitigations ---
    lines.append("## 11. Risks and Mitigations")
    lines.append("")
    risks = plan.get("risks_and_mitigations", [])
    if risks:
        lines.append("| Risk | Severity | Mitigation |")
        lines.append("|------|----------|------------|")
        for r in risks:
            lines.append(
                f"| {r.get('risk', '?')} | "
                f"{r.get('severity', 'Medium')} | "
                f"{r.get('mitigation', '?')} |")
    else:
        lines.append("_(No specific risks identified from ticket)_")
    lines.append("")

    # --- 12. Tools ---
    lines.append("## 12. Tools")
    lines.append("")
    lines.append(plan.get("tools",
        "_(Not specified — standard testing tools assumed)_"))
    lines.append("")

    # --- 13. Assumptions ---
    lines.append("## 13. Assumptions")
    lines.append("")
    assumptions = plan.get("assumptions", [])
    if assumptions:
        for a in assumptions:
            reason = a.get("reason", "unknown")
            lines.append(f"- **{ a.get('assumption', '?')}**")
            if reason == "not_in_ticket":
                lines.append(f"  � _Missing from ticket — requires confirmation_")
            else:
                lines.append(f"  _Reason: {reason}_")
    else:
        lines.append("_(No assumptions recorded)_")
    lines.append("")

    # --- 14. Trace Matrix ---
    lines.append("## 14. Trace Matrix")
    lines.append("")
    trace = plan.get("trace", [])
    if trace:
        lines.append("| Section | Source Fields | Has Assumptions |")
        lines.append("|---------|---------------|-----------------|")
        for t in trace:
            has_ass = "✅" if t.get("has_assumptions") else "✗"
            lines.append(
                f"| {t.get('section','?')} | "
                f"{', '.join(t.get('source_fields', []))} | {has_ass} |")
    else:
        lines.append("_(Trace data not available)_")
    lines.append("")

    # --- Appendix: Ticket Summary ---
    lines.append("---")
    lines.append("")
    lines.append(f"*Generated from Jira ticket [{key}]({ticket['url']}) — "
                f"Status: {ticket.get('status', '?')} | "
                f"Type: {ticket['issue_type']}*")
    if ticket["acceptance_criteria"]:
        lines.append("")
        lines.append(f"**Acceptance Criteria ({len(ticket['acceptance_criteria'])}):**")
        for ac in ticket["acceptance_criteria"]:
            lines.append(f"- {ac['text']}")

    return "\n".join(lines)